doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - assets
ignore-patterns:
  - (^|/)doc(/|$)
  - (^|/)migrations(/|$)
  - ^manage.py$
  - ^portailva/wsgi.py$
python-targets:
  - 3