version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-django
    ports:
      - "80:8000"
    depends_on:
      - app
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./static:/app/static

  app:
    build: .
    container_name: portailva
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn portailva.wsgi -b 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=portailva.settings_prod
      - DATABASE_HOST=db
      - DATABASE_USER=postgresql
      - DATABASE_PASSWORD=postgresql
      - DATABASE_NAME=portailva
      - DATABASE_PORT=5432

    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./static:/app/static

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_DB=portailva