version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-django
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles

  app:
    build: .
    container_name: portailva

    environment:
      - DATABASE_URL=postgres://postgresql@postgres/portailva
      - APP_DEBUG=True
      - SITE_DNS=web

    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_DB=portailva