# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0003_association_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'admin'),
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('position', models.IntegerField(blank=True, verbose_name='Position')),
                ('is_assignable', models.BooleanField(default=True, verbose_name='Est assignable ?')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Type MIME')),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Numéro de version')),
                ('data', models.FileField(upload_to='uploads/', verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file.File')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='association.Association', verbose_name='Association')),
            ],
            bases=('file.file',),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File', verbose_name='Fichier'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='filetag',
            name='allowed_types',
            field=models.ManyToManyField(blank=True, to='file.FileType', verbose_name='Extensions autorisées'),
        ),
        migrations.AddField(
            model_name='filetag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.FileTag', verbose_name='Tag parent'),
        ),
        migrations.AddField(
            model_name='associationfile',
            name='tags',
            field=models.ManyToManyField(to='file.FileTag', verbose_name='Tags'),
        ),
    ]
