# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('position', models.IntegerField(blank=True, verbose_name='Position')),
                ('allowed_types', models.ManyToManyField(blank=True, to='file.FileType', verbose_name='Extensions autorisées')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.FileFolder', verbose_name='Dossier parent')),
            ],
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='allowed_types',
        ),
        migrations.RemoveField(
            model_name='filetag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='associationfile',
            name='tags',
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file.File', verbose_name='Fichier'),
        ),
        migrations.DeleteModel(
            name='FileTag',
        ),
        migrations.AddField(
            model_name='associationfile',
            name='folder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file.FileFolder', verbose_name='Dossier'),
            preserve_default=False,
        ),
    ]
