# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20161016_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='is_writable',
            field=models.BooleanField(default=True, verbose_name='Accessible en écriture ?'),
        ),
    ]
