# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_filefolder_is_writable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.FileFolder', verbose_name='Dossier parent'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
