# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import portailva.file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20161024_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='data',
            field=models.FileField(upload_to=portailva.file.models.user_directory_path, verbose_name='Version'),
        ),
    ]
