# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20161102_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file.File')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
            options={
                'permissions': (('manage_resources', 'Gérer les resources disponibles aux associations'),),
            },
            bases=('file.file',),
        ),
    ]
