# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20170316_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='file.FileFolder', verbose_name='Dossier'),
        ),
    ]
