# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_resourcefile_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='file.ResourceFolder', verbose_name='Dossier parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='filefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='file.FileFolder', verbose_name='Dossier parent'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='file.ResourceFolder', verbose_name='Dossier'),
        ),
    ]
