# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20170321_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.FileFolder', verbose_name='Dossier parent'),
        ),
        migrations.AlterField(
            model_name='resourcefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file.ResourceFolder', verbose_name='Dossier parent'),
        ),
    ]
