# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20170321_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
