# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20161011_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est active'),
        ),
    ]
