# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_association_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begins_at', models.DateField(verbose_name='Début du mandat')),
                ('ends_at', models.DateField(verbose_name='Fin du mandat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='association.Association', verbose_name='Association')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=250, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de téléphone')),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='association.Mandate', verbose_name='Mandat')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du poste')),
                ('position', models.IntegerField(blank=True, default=1, verbose_name='Position')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoples', to='association.PeopleRole', verbose_name='Rôle'),
        ),
    ]
