# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_directoryentry_openinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryentry',
            name='association',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='place',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='directory_entry',
        ),
        migrations.DeleteModel(
            name='DirectoryEntry',
        ),
        migrations.DeleteModel(
            name='OpeningHour',
        ),
    ]
