# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_auto_20161102_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association', verbose_name='Association')),
            ],
            options={
                'permissions': (('achieve_requirement', 'Can achieve requirement'), ('unachieve_requirement', 'Can unachieve requirement')),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('mandate', 'Mandat'), ('file', 'Fichier'), ('accomplishment', 'Validation manuelle')], max_length=40, verbose_name='Type de condition')),
                ('data', models.TextField(blank=True, default='{}', verbose_name='Meta données')),
                ('active_until', models.DateTimeField(verbose_name='Date de fin de validité')),
            ],
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'default_permissions': ('add', 'change', 'delete', 'admin'), 'ordering': ('role',)},
        ),
        migrations.AlterModelOptions(
            name='peoplerole',
            options={'default_permissions': ('add', 'change', 'delete', 'admin'), 'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Requirement', verbose_name='Condition'),
        ),
    ]
