# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20161122_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name="Texte d'aide"),
        ),
    ]
