# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_requirement_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'default_permissions': ('achieve', 'unachieve')},
        ),
    ]
