# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_auto_20161123_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'default_permissions': ('add', 'change', 'delete', 'admin', 'achieve')},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'default_permissions': ('add', 'change', 'delete', 'admin'), 'ordering': ('name',)},
        ),
    ]
