# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0011_auto_20161123_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
    ]
