# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_association_active_members_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(help_text="Cette description n'est pas visible dans le Bot'INSA", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
    ]
