# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0013_auto_20170318_2142'),
        ('association', '0012_auto_20170318_2154'),
    ]

    operations = [
    ]
