# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_merge_20170320_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL du logo'),
        ),
    ]
