# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0015_association_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='bic',
            field=models.CharField(blank=True, max_length=15, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='association',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
    ]
