# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0016_auto_20171010_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Privilégier les liens en HTTPS', verbose_name='URL du logo'),
        ),
    ]
