# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 19:46
from __future__ import unicode_literals

from django.db import migrations
import portailva.utils.fields
import portailva.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0019_auto_20171013_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_url',
            field=portailva.utils.fields.LogoURLField(blank=True, help_text="Privilégiez les liens en HTTPS. Assurez-vous que le lien que vous fournissez pointe directement sur l'image (pas de page d'affichage comme Google Drive ou autres) et que l'image soit accessible.", validators=[portailva.utils.validators.validate_image_url], verbose_name='URL du logo'),
        ),
    ]
