# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import portailva.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0020_auto_20171013_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='iban',
            field=models.CharField(blank=True, max_length=50, validators=[portailva.utils.validators.validate_iban], verbose_name='IBAN'),
        ),
    ]
