# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-12 12:09
from __future__ import unicode_literals

from django.db import migrations
import portailva.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0022_auto_20171112_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_url',
            field=portailva.utils.fields.LogoURLField(blank=True, help_text="Privilégiez les liens en HTTPS. Assurez-vous que le lien que vous fournissez pointe directement sur l'image (pas de page d'affichage comme Google Drive ou autres) et que l'image soit accessible.", verbose_name='URL du logo'),
        ),
    ]
