# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0005_auto_20161102_1505'),
        ('utils', '0001_initial'),
        ('association', '0007_auto_20161102_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name="Description de l'association")),
                ('contact_address', models.EmailField(max_length=254, verbose_name='Adresse de contact')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='URL site web')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='URL page Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='URL fil Twitter')),
                ('is_online', models.BooleanField(default=False, verbose_name='Est publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_entries', to='association.Association', verbose_name='Association')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.File', verbose_name='Logo')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='utils.Place', verbose_name='Lieu')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'admin'),
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name="Jour d'ouverture")),
                ('begins_at', models.TimeField(verbose_name="Heure d'ouverture")),
                ('ends_at', models.TimeField(verbose_name='Heure de fermeture')),
                ('directory_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='directory.DirectoryEntry', verbose_name="Version du Bot'INSA")),
            ],
            options={
                'ordering': ('day', 'begins_at'),
                'default_permissions': ('add', 'change', 'delete', 'admin'),
            },
        ),
    ]
