# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 21:52
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0002_remove_directoryentry_logo'),
    ]

    operations = [
        UnaccentExtension()
    ]
