# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0005_auto_20161102_1505'),
        ('association', '0007_auto_20161102_1505'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('short_description', models.TextField(max_length=150, verbose_name='Description courte')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_online', models.BooleanField(default=False, verbose_name='Est publié')),
                ('begins_at', models.DateTimeField(verbose_name='Date de début')),
                ('ends_at', models.DateTimeField(verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='association.Association', verbose_name='Association')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.File', verbose_name='Image')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='utils.Place', verbose_name='Lieu')),
            ],
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du tarif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarif')),
                ('is_va', models.BooleanField(default=False, verbose_name='Est un tarif VA ?')),
                ('is_variable', models.BooleanField(default=False, verbose_name='Prix libre ?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='event.Event', verbose_name='Evénement')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event.EventType', verbose_name="Type d'événement"),
        ),
    ]
