# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ('add', 'change', 'delete', 'admin')},
        ),
        migrations.AlterModelOptions(
            name='eventprice',
            options={'default_permissions': ('add', 'change', 'delete', 'admin')},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'default_permissions': ('add', 'change', 'delete', 'admin')},
        ),
    ]
