# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161102_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begins_at',
            field=models.DateTimeField(verbose_name='Date et heure de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='utils.Place', verbose_name='Lieu'),
        ),
    ]
