# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 14:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161102_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tarif'),
        ),
    ]
