# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20161104_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Page web'),
        ),
    ]
