# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Privilégier les liens en HTTPS', verbose_name='URL du logo'),
        ),
    ]
