# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('loc_x', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Longitude')),
                ('loc_y', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitude')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'admin'),
            },
        ),
    ]
