# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='loc_x',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='loc_y',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Longitude'),
        ),
    ]
