# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20171010_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='loc_y',
            new_name='long',
        ),
    ]
