# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0004_auto_20161104_1418'),
        ('association', '0011_auto_20161123_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('author', models.CharField(max_length=255, verbose_name='Auteur')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated', models.BooleanField(verbose_name='publié')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='contenu')),
                ('type', models.CharField(choices=[('FEATURED', 'A la une'), ('CLASSIC', 'Normal')], max_length=20, verbose_name='type')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='association.Association', verbose_name='Association')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleNewsletterElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventNewsletterElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nom')),
                ('sent', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newletter', to='newsletter.ArticleNewsletterElement', verbose_name='Articles')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newletter', to='newsletter.EventNewsletterElement', verbose_name='Evènements')),
            ],
        ),
    ]
