# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='publié'),
        ),
    ]
