# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20170106_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('FEATURED', 'A la une'), ('CLASSIC', 'Normal')], default='CLASSIC', max_length=20, verbose_name='type'),
        ),
    ]
