# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20170131_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenewsletterelement',
            name='article',
        ),
        migrations.RemoveField(
            model_name='eventnewsletterelement',
            name='event',
        ),
        migrations.AddField(
            model_name='article',
            name='short_content',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(related_name='newletter', to='newsletter.Article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='events',
            field=models.ManyToManyField(related_name='newletter', to='event.Event', verbose_name='Evènements'),
        ),
        migrations.DeleteModel(
            name='ArticleNewsletterElement',
        ),
        migrations.DeleteModel(
            name='EventNewsletterElement',
        ),
    ]
