# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20170131_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
