# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 16:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20170131_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default=None, help_text="Cette image est utilisée dans l'envoie de la newsletter VA", upload_to='', verbose_name='Image à la une'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_content',
            field=models.CharField(max_length=255, verbose_name='Description courte'),
        ),
    ]
