# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20170310_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(related_name='newsletter', to='newsletter.Article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='events',
            field=models.ManyToManyField(related_name='newsletter', to='event.Event', verbose_name='Evènements'),
        ),
    ]
